name: Deploy ETL StepFunctions

# When this action should be invoked
on:
  # On clicking the dispatch button
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ETLStepFunctionDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from main branch
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION_NAME }}

      - name: Deploy StepFunctions Stepmachine for Lambda Functions
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: ETLStepFunctions
          template: cf-templates/templates/ETLStepFunctions.json
